config/routes.rb
FoodDiary::Application.routes.draw do
  resources :entries
  root 'entries#index'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
	validates :food, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render action: 'show', status: :created, location: @entry }
      else
        format.html { render action: 'new' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:date, :time, :food, :situation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation" class="message error">
        <h2>Oops! We found <%= pluralize(@entry.errors.count, "error") %></h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_select :date, {:order=>[:day, :month, :year], :class=>"input-lg form-control"} %>
  </div>
  <div class="field">
    <%= f.label :time, 'Time:' %>
    <%= f.time_select :time %>
  </div>
  <div class="field">
    <%= f.label :food %><br>
    <%= f.text_area :food %>
  </div>
  <div class="field">
    <%= f.label :situation %><br>
    <%= f.text_area :situation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path,  {:class=>'button-gray'} %>

app/views/entries/index.html.erb
<% date = "" %>
<% @entries.order(:date).order(:time).reverse_order.each do |entry| %>
  <% if date != entry.date %>
    <% date = entry.date %>
    <div class="date"><%= date.strftime("%B %-d, %G") %></div>
  <% end %>
    <div class="entry" id="<%= dom_id(entry) %>">
      <div class="edit">
         <%= link_to 'Edit', edit_entry_path(entry) %>
         <%= link_to 'Delete', entry, method: :delete, data: { confirm: 'Are you sure?' }  %>
      </div>
     
      <div class="time"><%= entry.time.strftime("%l:%M %p") %></div>
      <%= link_to entry do %>
        <div class="food"><%= entry.food %></div>
      <% end %>
      <div class="situation"><%= entry.situation %></div>
    </div>
  
<% end %>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path, {:class=>'button-gray'} %>

app/views/entries/show.html.erb
<div class="message success"><h2><%= notice %></h2></div>

<div class="date"><%= @entry.date.strftime("%B %C, %G") %></div>

<div class="entry">
	<div class="edit">
 		<%= link_to 'Edit', edit_entry_path %>
 	</div>
  <div class="time"><%= @entry.time.strftime("%l:%M %p") %></div>
  <div class="food"><%= @entry.food %></div>
  <div class="situation"><%= @entry.situation %></div>
</div>

<%= link_to 'Done', entries_path, {:class=>'btn btn-success btn-large pull-right'} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FoodDiary</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Dosis:400,700" %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top">

    <div class="container">
    <%= link_to "New", new_entry_path, {:class=>"btn btn-success navbar-right navbar-btn"} %>
    <%= link_to "Food Diary", entries_path, {:class=>"navbar-brand"} %>
    </div>
	</nav>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>